const mongoose = require('mongoose');

const SubjectSchema = new mongoose.Schema({
  // `code` may be generated by the controller if omitted by admin UI,
  // so make it optional at schema level but keep uniqueness when present.
  code: { type: String, unique: true, trim: true, sparse: true },
  title: { type: String, required: true, trim: true },
  capacity: { type: Number, default: 30 },
  instructor: { type: mongoose.Schema.Types.ObjectId, ref: 'Faculty' },
  // academic targeting
  year: { type: Number, required: true },
  semester: { type: Number, required: true },
  department: { type: String },
  // additional details for display
  credits: { type: Number, default: 3 },
  hours: { type: Number, default: 3 },
  description: { type: String },
  topics: [{ type: String }],
  faculty: { type: String }, // Faculty name as text for display
  // sections: optional array of sections with independent capacities
  sections: [{ name: String, capacity: Number }],
}, { timestamps: true });

// Helpful compound index for filtering by academic cohort
SubjectSchema.index({ year: 1, semester: 1 });

module.exports = mongoose.model('Subject', SubjectSchema);
